### ISSUE TITLE
I'm getting a value error 

### ISSUE THREAD

**Issue by ikiran-dev** [adityaintwala/Image2CAD#1]
Not enough values to unpack ![IMG_20220422_145057.jpg](https://user-images.githubusercontent.com/59160552/164677039-6b1edde1-27d5-4bdc-98c7-12b6c3230208.jpg)

**Comment by adityaintwala** [comment]
Hello,
Thank you for your interest. 
The issue is due to the difference in number of return values in newer OpenCV library, please use the recommended one i.e version 3 rather than version 4, else please remove the hierarchy value.

Please Note : you will have to do similar change in some other part as well if you go ahead with upgrading the library.

Thanks
